config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  resources :produits

  resources :checkout, only:[:create]
  post "checkout/create", to: "checkout#create"

  get "success", to: "checkout#success"
  get "cancel", to: "checkout#cancel"

  resources :webhooks, only: [:create]
  get "success", to: "checkout#success"
  get "cancel", to: "checkout#cancel"

  root "produits#index"

  #post "produits/add_to_cart/:id", to: "produits#add_to_cart", as: "add_to_cart"
  #delete "produits/remove_from_cart/:id", to: "produits#remove_from_cart", as: "remove_from_cart"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produit.rb
class Produit < ApplicationRecord
    validates :name, :price, presence: true

    monetize :price, as: :price_cent

    def to_s
        name
    end

    after_create do
        product = Stripe::Product.create(name: name)
      
        one_time_price = Stripe::Price.create(product: product, unit_amount: self.price, currency: 'eur')
      
        subscription_price = Stripe::Price.create({
          product: product,
          recurring: {
            interval: 'month',
          },
          unit_amount: self.price/12, # Set the subscription price amount here
          currency: 'eur',
        })
      
        update(stripe_product_id: product.id, stripe_price_id: one_time_price.id, stripe_subscription_price_id: subscription_price.id)
      end

    after_update do
        product = Stripe::Product.update(stripe_product_id, {name: name})
    end

    after_update  :create_and_assign_new_stripe_price, if: :saved_change_to_price?

    def create_and_assign_new_stripe_price 
        one_time_price = Stripe::Price.create(
            product: self.stripe_product_id, 
            unit_amount: self.price, 
            currency: 'eur')

        subscription_price = Stripe::Price.create(
            product: self.stripe_product_id, 
            recurring: {
                interval: 'month',
            },
            unit_amount: self.price/12, # Set the subscription price amount here
            currency: 'eur')

        update(stripe_price_id: one_time_price.id, stripe_subscription_price_id: subscription_price.id )
    end



    # tests sur subscriptions pour check si customer has one 

    def check_subscription(customer_id, product_id)
        subscriptions = Stripe::Subscription.list
      
        subscriptions_for_customer = subscriptions.select do |subscription|
          subscription.customer == customer_id && subscription.plan.product == product_id
        end
      
        if subscriptions_for_customer.present?
          valid_subscriptions = subscriptions_for_customer.select { |subscription| subscription_valid?(subscription) }
          valid_subscriptions.present?
        else
          false
        end
      end
      
      def subscription_valid?(subscription)
        return false unless subscription.status == 'active'
      
        invoice = Stripe::Invoice.retrieve(subscription.latest_invoice)
        return false unless invoice.status == 'paid'
      
        subscription.current_period_end > Time.now.to_i
      end
      
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

def create
  product = Produit.find(params[:id])
  
  if params[:payment_mode] == 'subscription'
    session = Stripe::Checkout::Session.create({
      mode: 'subscription',
      payment_method_types: ['card'],
      line_items: [
        {
          price: product.stripe_subscription_price_id,
          quantity: 1,
        }
      ],
      success_url: success_url + "?session_id={CHECKOUT_SESSION_ID}",
      cancel_url: cancel_url,
    })
  else
    session = Stripe::Checkout::Session.create({
      mode: 'payment',
      payment_method_types: ['card'],
      line_items: [
        {
          price: product.stripe_price_id,
          quantity: 1,
        }
      ],
      success_url: success_url + "?session_id={CHECKOUT_SESSION_ID}",
      cancel_url: cancel_url,
    })
  end

  redirect_to session.url, allow_other_host: true, status: 303
end
  

  def success
    @session_with_expand = Stripe::Checkout::Session
      .retrieve({ id: params[:session_id], expand: ["line_items"] }) 

    @session_with_expand.line_items.data.each do |line_item|
      @product_id = Produit.find_by(stripe_product_id: line_item.price.product)
    end

  end

  def cancel
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  before_action :set_produit, only: %i[ show edit update destroy ]

  # GET /produits or /produits.json
  def index
    @produits = Produit.all
  end

  # GET /produits/1 or /produits/1.json
  def show
  end

  # GET /produits/new
  def new
    @produit = Produit.new
  end

  # GET /produits/1/edit
  def edit
  end

  # POST /produits or /produits.json
  def create
    @produit = Produit.new(produit_params)

    respond_to do |format|
      if @produit.save
        format.html { redirect_to produit_url(@produit), notice: "Produit was successfully created." }
        format.json { render :show, status: :created, location: @produit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produits/1 or /produits/1.json
  def update
    respond_to do |format|
      if @produit.update(produit_params)
        format.html { redirect_to produit_url(@produit), notice: "Produit was successfully updated." }
        format.json { render :show, status: :ok, location: @produit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1 or /produits/1.json
  def destroy
    @produit.destroy

    respond_to do |format|
      format.html { redirect_to produits_url, notice: "Produit was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produit
      @produit = Produit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produit_params
      params.require(:produit).permit(:name, :price, :price_cent, :stripe_subscription_price_id)
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
   # skip_before_action :authenticate_user!
    skip_before_action :verify_authenticity_token
  
   def create
      payload = request.body.read
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      event = nil
  
      begin
        event = Stripe::Webhook.construct_event(
          payload, sig_header, ENV['STRIPE_WEBHOOK_KEY'] # Use environment variable for production
        )
      rescue JSON::ParserError => e
        status 400
        return
      rescue Stripe::SignatureVerificationError => e
        # Invalid signature
        puts "Signature error"
        p e
        return
      end
  
      # Handle the event
      case event.type
      when 'checkout.session.completed'
        session = event.data.object
        session_with_expand = Stripe::Checkout::Session.retrieve({ id: session.id, expand: ["line_items"]})
        session_with_expand.line_items.data.each do |line_item|
          product = Produit.find_by(stripe_product_id: line_item.price.product)
          product.increment!(:sales_count)
        end
      end
  
      render json: { message: 'success' }
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/views/checkout/cancel.html.erb
<h1> cancel page </h1>

app/views/checkout/success.html.erb
<h1> success page </h1>

Checkout status: <%= @session_with_expand.payment_status %> <br>

Product bought: <%= @product_id  %> <br>

Price paid: <%= @session_with_expand.amount_total/100.to_f %>
 <%= @session_with_expand.currency %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppStripe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= link_to "produits", produits_path%>     
    <%= yield %>
  </body>
</html>

app/views/produits/_form.html.erb
<%= form_with(model: produit) do |form| %>
  <% if produit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produit.errors.count, "error") %> prohibited this produit from being saved:</h2>

      <ul>
        <% produit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price_cent, style: "display: block" %>
    <%= form.text_field :price_cent %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/produits/_produit.html.erb
<div id="<%= dom_id produit %>">
  <p>
    <strong>Name:</strong>
    <%= produit.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= produit.price_cent %>
  </p>


    <div data-turbo='false'>
      <%#= button_to  "buy", checkout_create_path, params: {id: produit.id}, 
          remote: true %>
    </div>


    <div>

      <% customer_id = 'cus_OFGtmZr1mTS2aA' %> 
      <%# à remplacer par id dynamqiue
      id stripe du current user 
       %>
      
      <% product_id = produit.stripe_product_id %>

      <% has_subscription = produit.check_subscription(customer_id, product_id) %>

      <% if has_subscription %>
        <p>The customer has a subscription for the product.</p>
      <% else %>
        <p>The customer does not have a subscription for the product.</p>
      <% end %>

        
    </div>

  </div>

</div>

app/views/produits/edit.html.erb
<h1>Editing produit</h1>

<%= render "form", produit: @produit %>

<br>

<div>
  <%= link_to "Show this produit", @produit %> |
  <%= link_to "Back to produits", produits_path %>
</div>

app/views/produits/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>sales count</th>
      <th>Stripe produit id </th>
      <th>Stripe price id </th>
      <th>Shopping cart </th>
      <th>PAYMENT </th>
      <th>subscription</th>
    </tr>
  </thead>

  <tbody>

  <% if @produits.present? %>
    <% @produits.each do |produit| %>
      <tr>
        <td><%= produit.name %></td>
        <td><%= number_to_currency(produit.price_cent) %></td>
        <td><%= produit.sales_count %> </td>
        <td><%=  truncate( produit.stripe_product_id, :length => 10)  %> </td>
        <td><%=  truncate( produit.stripe_price_id, :length => 10) %> </td>

        <td>
          <div data-turbo='false'>
            <%= button_to  "buy", checkout_create_path, params: {
              id: produit.id,
              payment_mode: 'payment'
              }, remote: true %>
          </div>
        </td>

        <td>
          <div data-turbo='false'>
            <%= button_to "Subscribe", checkout_create_path, params: {
              id: produit.id,
              payment_mode: 'subscription'
            }, remote: true %>
          </div>
        </td>

        <td><%= link_to 'Show', produit %></td>
        <td><%= link_to 'edit', edit_produit_path(produit) %></td>        
        <td><%= link_to 'Destroy', produit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_produit_path %>

app/views/produits/new.html.erb
<h1>New produit</h1>

<%= render "form", produit: @produit %>

<br>

<div>
  <%= link_to "Back to produits", produits_path %>
</div>

app/views/produits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produit %>

<div>
  <%= link_to "Edit this produit", edit_produit_path(@produit) %> |
  <%= link_to "Back to produits", produits_path %>

  <%= button_to "Destroy this produit", @produit, method: :delete %>
</div>